spring:
  datasource:
    url: jdbc:mysql://localhost:3306/serviceformation?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    open-in-view: true
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
#        session_factory:
#          interceptor: com.bouali.gestiondestock.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect


server:
  port: 8080

#flickr:
#  apiKey: e6017aef7bebeffc113de04efec554b4
#  apiSecret: a2e10f69ece5c67c
#  appKey: 72157718699655397-a36ae267891db7e7
#  appSecret: 04e870e57e18c55b
